name: My Workflow
on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build -t my-docker-image .

      - name: Run Docker container
        run: |
          docker run -d --name my-container -v "$(pwd)":/app my-docker-image
          sleep 5 # wait for the container to start
          docker exec my-container ls -la /app # list the files in the mounted volume
