name: My Workflow
on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build -t my-docker-image .
        
      - name: Run Docker container
        run: docker run -a stderr -a stdout --name my-container -v "$(pwd)":/app my-docker-image . .github/scripts/build-rust.sh
