name: My Workflow
on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: |
            /var/lib/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: docker build -t my-docker-image .

      - name: Build Rust
        run: |
          chmod +x ./.github/scripts/build-rust.sh
          docker run -a stderr -a stdout --name my-container -v "$(pwd)":/app my-docker-image sh -c "/app/.github/scripts/build-rust.sh"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libs
          path: /app/bin/