name: Build
on: [push]

jobs:
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Rust
        run: |
          chmod +x ./.github/scripts/build-rust.sh
          sh -c "./.github/scripts/build-rust.sh"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rust-libs
          path: ${{ github.workspace }}/bin/

  build-bindings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Build
        run: |
          chmod +x ./.github/scripts/build-bindings.sh
          sh -c "./.github/scripts/build-bindings.sh"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bindings
          path: ${{ github.workspace }}/bin/

  combine:
    runs-on: ubuntu-latest
    needs: [build-rust, build-bindings]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: rust-libs
          path: ${{ github.workspace }}/bin/

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: bindings
          path: ${{ github.workspace }}/bin/

      - name: Print directory
        run: |
          ls -la ${{ github.workspace }}/bin/