name: My Workflow
on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build -t my-docker-image .
        
      - name: Run Docker container
        run: |
          docker run -d --name my-container -v "$(pwd)":/app my-docker-image ls -la /app 
          
      - name: Get Docker container output
        run: |
          CONTAINER_OUTPUT=$(docker logs my-container)
          echo "The container output is: $CONTAINER_OUTPUT"
