name: My Workflow
on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build -t my-docker-image .
      
      - name: Load Docker image
        run: docker load < my-docker-image.tar
      
      - name: Run command in container
        run: docker run my-docker-image echo "Hello, world!"
